version: '3'
services:
  database:
    container_name: 'database'
    image: mysql
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_DATABASE: backend_rest_api
    ports:
      - "3306:3306"
    restart: always
  api:
    build: .
    ports:
    - "8083:8083"
    depends_on:
      - database